### ISSUE TITLE
nullpointerexception when use componente with Windows Form

### ISSUE THREAD

**Issue by marlondivino** [Federerer/Notifications.Wpf#1]
I think the problem is when using "Application.Current.Dispatcher" instead of "Dispatcher.CurrentDispatcher"

**Comment by Federerer** [comment]
Thanks for finding this. I have little experience with Windows Forms.
It should work now. If Application.Current is null then NotificationManager uses Dispatcher.CurrentDispatcher. If you creating NotificationManager not from UI thread you could also provide the right dispatcher in constructor:
```C#
var manager = new NotificationManager(uiThreadDispatcher);
            manager.Show("Some text");
```
