### ISSUE TITLE
Toast location

### ISSUE THREAD

**Issue by ghost** [Federerer/Notifications.Wpf#16]
Hi there,

Despite following the instructions, I can't change the toast location - it is always bottom-right.

I declare the area in mainwindow xaml but it seems to be ignored.

A simple example in VB would be appreciated?

Thank you

**Comment by mxmissile** [comment]
I placed mine in a grid, shows exactly where I tell it to:

`<controls:NotificationArea x:Name="WindowArea" Position="TopLeft" MaxItems="3"  Grid.Row="1"/>`
