### ISSUE TITLE
Close a notification

### ISSUE THREAD

**Issue by sadri31000** [Federerer/Notifications.Wpf#22]
Hello,
Is there a way to close a shown notification ? from another button from example
thx

**Comment by mxmissile** [comment]
Looking through the source code, there is nothing that would enable this. However, it looks very simple to add, in theory you could add a `Show()` overload that returns the Window object, then call `Close()` on that. For example after adding the overload you could:

```
var window = _notificationManager.Show(...);
window.Close();
```

**Comment by sadri31000** [comment]
Hello,
yes thank you for quick response
