### ISSUE TITLE
hi How custom ICONS

### ISSUE THREAD

**Issue by FastChen** [Federerer/Notifications.Wpf#4]
<Path x:Key="TrophyIcon" Data="M458 653q-74 162 -74 371h-256v-96q0 -78 94.5 -162t235.5 -113zM1536 928v96h-256q0 -209 -74 -371q141 29 235.5 113t94.5 162zM1664 1056v-128q0 -71 -41.5 -143t-112 -130t-173 -97.5t-215.5 -44.5q-42 -54 -95 -95q-38 -34 -52.5 -72.5t-14.5 -89.5q0 -54 30.5 -91 t97.5 -37q75 0 133.5 -45.5t58.5 -114.5v-64q0 -14 -9 -23t-23 -9h-832q-14 0 -23 9t-9 23v64q0 69 58.5 114.5t133.5 45.5q67 0 97.5 37t30.5 91q0 51 -14.5 89.5t-52.5 72.5q-53 41 -95 95q-113 5 -215.5 44.5t-173 97.5t-112 130t-41.5 143v128q0 40 28 68t68 28h288v96 q0 66 47 113t113 47h576q66 0 113 -47t47 -113v-96h288q40 0 68 -28t28 -68z" Fill="White" x:Shared="False"/>

this is PackIconFontAwesome ico data How does ability let him show
Or what the icon here in the what data?

pls tell me

**Comment by Federerer** [comment]
If I understood you correctly, to use custom icons, You need to override default template for Notification control. Check the sample project:
https://github.com/Federerer/Notifications.Wpf/blob/master/Notifications.Wpf.Sample/App.xaml#L11-L23
or when using Caliburn.Micro just create ViewModel and corresponding View for your model.

**Comment by FastChen** [comment]
Ok, thank you
